// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/goingenterprise/petstore-go-sdk/models/components"
)

type CreatePetsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// unexpected error
	Error *components.Error
}

func (o *CreatePetsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreatePetsResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
