// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/goingenterprise/petstore-go-sdk/models/components"
)

type ShowPetByIDRequest struct {
	// The id of the pet to retrieve
	PetID string `pathParam:"style=simple,explode=false,name=petId"`
}

func (o *ShowPetByIDRequest) GetPetID() string {
	if o == nil {
		return ""
	}
	return o.PetID
}

type ShowPetByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Expected response to a valid request
	Pet *components.Pet
	// unexpected error
	Error *components.Error
}

func (o *ShowPetByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ShowPetByIDResponse) GetPet() *components.Pet {
	if o == nil {
		return nil
	}
	return o.Pet
}

func (o *ShowPetByIDResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
