// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Pet struct {
	ID   int64   `json:"id"`
	Name string  `json:"name"`
	Tag  *string `json:"tag,omitempty"`
}

func (o *Pet) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Pet) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Pet) GetTag() *string {
	if o == nil {
		return nil
	}
	return o.Tag
}
